src/Entity/Event.php
<?php

namespace App\Entity;

use App\Repository\EventRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: EventRepository::class)]
class Event
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    private ?string $title = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column(length: 100, nullable: true)]
    private ?string $lieu = null;

    #[ORM\Column]
    private ?bool $public = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $event_start = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $event_end = null;

    #[ORM\Column(length: 7)]
    private ?string $background_color = null;
   
    #[ORM\Column(length: 7)]
    private ?string $border_color = null;

    #[ORM\Column(length: 7)]
    private ?string $text_color = null;

    #[ORM\ManyToOne(inversedBy: 'events')]
    private ?MusicGroup $music_group = null;

    #[ORM\ManyToMany(targetEntity: User::class, inversedBy: 'events')]
    private Collection $invite;

    public function __construct()
    {
        $this->invite = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getLieu(): ?string
    {
        return $this->lieu;
    }

    public function setLieu(?string $lieu): self
    {
        $this->lieu = $lieu;

        return $this;
    }

    public function isPublic(): ?bool
    {
        return $this->public;
    }

    public function setPublic(bool $public): self
    {
        $this->public = $public;

        return $this;
    }

    public function getEventStart(): ?\DateTimeInterface
    {
        return $this->event_start;
    }

    public function setEventStart(\DateTimeInterface $event_start): self
    {
        $this->event_start = $event_start;

        return $this;
    }

    public function getEventEnd(): ?\DateTimeInterface
    {
        return $this->event_end;
    }

    public function setEventEnd(\DateTimeInterface $event_end): self
    {
        $this->event_end = $event_end;

        return $this;
    }

    public function getBackgroundColor(): ?string
    {
        return $this->background_color;
    }

    public function setBackgroundColor(string $background_color): self
    {
        $this->background_color = $background_color;

        return $this;
    }

    public function getBorderColor(): ?string
    {
        return $this->border_color;
    }

    public function setBorderColor(string $border_color): self
    {
        $this->border_color = $border_color;

        return $this;
    }

    public function getTextColor(): ?string
    {
        return $this->text_color;
    }

    public function setTextColor(string $text_color): self
    {
        $this->text_color = $text_color;

        return $this;
    }

    public function getMusicGroup(): ?MusicGroup
    {
        return $this->music_group;
    }

    public function setMusicGroup(?MusicGroup $music_group): self
    {
        $this->music_group = $music_group;

        return $this;
    }

    /**
     * @return Collection<int, User>
     */
    public function getInvite(): Collection
    {
        return $this->invite;
    }

    public function addInvite(User $invite): self
    {
        if (!$this->invite->contains($invite)) {
            $this->invite->add($invite);
        }

        return $this;
    }

    public function removeInvite(User $invite): self
    {
        $this->invite->removeElement($invite);

        return $this;
    }

}

src/Controller/Front/AlbumController.php
<?php

namespace App\Controller\Front;

use App\Entity\MusicGroup;
use App\Entity\Album;
use App\Entity\Music;
use App\Form\AlbumType;
use App\Repository\AlbumRepository;
use App\Repository\MusicGroupRepository;
use App\Repository\MusicRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Exception\AccessDeniedException;
use App\Security\Voter\MusicGroupManagerAccesVoter;


// #[Route('/album')]
class AlbumController extends AbstractController
{
    #[Route('/album', name: 'app_album_index', methods: ['GET'])]
    public function index(AlbumRepository $albumRepository): Response
    {
        return $this->render('front/album/index.html.twig', [
            'albums' => $albumRepository->findAll(),
        ]);
    }




    #[Route('/music_group/{id}/album/new', name: 'app_album_new', methods: ['GET', 'POST'])]
    public function new(Request $request, AlbumRepository $albumRepository, MusicGroup $musicGroup, MusicGroupRepository $musicGroupRepository, MusicRepository $musicRepository): Response
    {

        //vérifie si le user est un manager
        $this->denyAccessUnlessGranted('ROLE_MANAGER');

        //vérifie si le user est le manager du groupe 
        if (!$this->isGranted(MusicGroupManagerAccesVoter::MANAGER_ACCESS, $musicGroup)) {
            throw new AccessDeniedException();
        }

        $album = new Album();
        // $musics = $musicGroup->getMusic();

        // $musics = $musicRepository->findUnassignedMusic();
        $musics = $musicGroupRepository->find($musicGroup->getId())->getMusic()->filter(function(Music $music) {
            return $music->getAlbum() === null;
        });

        $form = $this->createForm(AlbumType::class, $album, ['musicGroup' => $musicGroup, 'edit' => false]);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $album->setMusicGroup($musicGroup);

            $selectedMusics = $album->getMusic();
            foreach ($selectedMusics as $selectedMusic) {
                $music = $musicRepository->find($selectedMusic);
                $music->setAlbum($album);
                $musicRepository->save($music, true);
            }

            $image = $form->get('image')->getData();
            $image->move($this->getParameter('images_directory'), $image->getClientOriginalName());
            $album->setImage($image->getClientOriginalName());
            $albumRepository->save($album, true);
        
            return $this->redirectToRoute('front_app_music_group_show', ['id' => $musicGroup->getId()], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('front/album/new.html.twig', [
            'album' => $album,
            'form' => $form,
            'musics' => $musics,
        ]);
    }




    #[Route('/album/{id}', name: 'app_album_show', methods: ['GET'])]
    public function show(Album $album): Response
    {
        $musics = $album->getMusic();
        $musicList = [];
        foreach ($musics as $music) {
            $musicList[] = $music;
        }
        
        return $this->render('front/album/show.html.twig', [
            'album' => $album,
            'musicList' => $musicList,
        ]);
    }




    #[Route('/album/{id}/edit', name: 'app_album_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Album $album, AlbumRepository $albumRepository, MusicGroupRepository $musicGroupRepository, MusicRepository $musicRepository): Response
    {
        $musicGroup = $album->getMusicGroup();
        //vérifie si le user est un manager
        $this->denyAccessUnlessGranted('ROLE_MANAGER');

        //vérifie si le user est le manager du groupe 
        if (!$this->isGranted(MusicGroupManagerAccesVoter::MANAGER_ACCESS, $musicGroup)) {
            throw new AccessDeniedException();
        }

        $form = $this->createForm(AlbumType::class, $album, ['musicGroup' => $musicGroup, 'edit' => true]);

        $form->handleRequest($request);

        //dd( $form->handleRequest($request));

        
        if ($form->isSubmitted() && $form->isValid()) {

            $image = $form->get('image')->getData();

            $image->move($this->getParameter('images_directory'), $image->getClientOriginalName());
            $album->setImage($image->getClientOriginalName());
            if ($image == null) {
                $album->setImage('empty');
            }

            $albumRepository->save($album, true);

            return $this->redirectToRoute('app_album_show', ['id' => $album->getId()], Response::HTTP_SEE_OTHER);
        }

        $albumMusics = $album->getMusic();

        return $this->renderForm('front/album/edit.html.twig', [
            'album' => $album,
            'form' => $form,
            'albumMusics' => $albumMusics,
        ]);
    }

    #[Route('/album/{id}', name: 'app_album_delete', methods: ['POST'])]
    public function delete(Request $request, Album $album, AlbumRepository $albumRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$album->getId(), $request->request->get('_token'))) {
            $albumRepository->remove($album, true);
        }

        return $this->redirectToRoute('app_album_index', [], Response::HTTP_SEE_OTHER);
    }
}

src/Controller/Front/CommentController.php
<?php

namespace App\Controller\Front;

use App\Entity\Comment;
use App\Form\CommentType;
use App\Repository\CommentRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/comment')]
class CommentController extends AbstractController
{
    #[Route('/', name: 'app_comment_index', methods: ['GET'])]
    public function index(CommentRepository $commentRepository): Response
    {
        return $this->render('front/comment/index.html.twig', [
            'comments' => $commentRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_comment_new', methods: ['GET', 'POST'])]
    public function new(Request $request, CommentRepository $commentRepository): Response
    {
        $comment = new Comment();
        $form = $this->createForm(CommentType::class, $comment);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $commentRepository->save($comment, true);

            return $this->redirectToRoute('front_app_comment_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('front/comment/new.html.twig', [
            'comment' => $comment,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_comment_show', methods: ['GET'])]
    public function show(Comment $comment): Response
    {
        return $this->render('front/comment/show.html.twig', [
            'comment' => $comment,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_comment_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Comment $comment, CommentRepository $commentRepository): Response
    {
        $form = $this->createForm(CommentType::class, $comment);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $commentRepository->save($comment, true);

            return $this->redirectToRoute('front_app_comment_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('front/comment/edit.html.twig', [
            'comment' => $comment,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_comment_delete', methods: ['POST'])]
    public function delete(Request $request, Comment $comment, CommentRepository $commentRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$comment->getId(), $request->request->get('_token'))) {
            $commentRepository->remove($comment, true);
        }

        return $this->redirectToRoute('front_app_comment_index', [], Response::HTTP_SEE_OTHER);
    }
}

src/Controller/Front/DefaultController.php
<?php

namespace App\Controller\Front;

use App\Repository\UserRepository;
use App\Repository\MusicGroupRepository;

use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Authorization\AuthorizationCheckerInterface;


#[IsGranted('ROLE_FAN')]
class DefaultController extends AbstractController
{
    #[Route('/', name: 'default_index')]
    public function index(): Response
    {
        return $this->render('front/default/index.html.twig');
    }

    #[Route('/artists', name: 'default_artists')]
    public function getAllArtists(UserRepository $userRepository): Response
    {
        $artists = $userRepository->findByRole('ROLE_ARTIST');
        return $this->render('front/default/artist/index.html.twig', [
            'artists' => $artists
        ]);
    }

    #[Route('/artist/{id}', name: 'default_artist')]
    public function getArtist(UserRepository $userRepository, $id, AuthorizationCheckerInterface $authorizationChecker): Response
    {
        $artist = $userRepository->find($id);

        $roles = $artist->getRoles();

        // Récupérer le rôle le plus haut
        $highestRole = '';
        foreach ($roles as $role) {
            if ($authorizationChecker->isGranted($role)) {
                $highestRole = $role;
                break;
            }
        }

        $music_groups = $artist->getMusicGroups();

        return $this->render('front/default/artist/show_artist.html.twig', [
            'artist' => $artist,
            'highestRole' => $highestRole,
            'music_groups' => $music_groups,
        ]);
    }

    #[Route('/music_groups', name: 'default_music_groups')]
    public function getAllMusicGroups(MusicGroupRepository $musicGroupRepository): Response
    {
        $music_groups = $musicGroupRepository->findAll();
        return $this->render('front/music_group/index.html.twig', [
            'music_groups' => $music_groups
        ]);
    }

    #[Route('/email_template', name: 'default_email_template')]
    public function emailTemplate(MusicGroupRepository $musicGroupRepository): Response
    {
        return $this->render('front/email/registrationEmail.html.twig');
    }
}

src/Controller/Front/DocumentController.php
<?php

namespace App\Controller\Front;

use App\Entity\Document;
use App\Form\DocumentType;
use App\Repository\DocumentRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/document')]
class DocumentController extends AbstractController
{
    #[Route('/', name: 'app_document_index', methods: ['GET'])]
    public function index(DocumentRepository $documentRepository): Response
    {
        return $this->render('front/document/index.html.twig', [
            'documents' => $documentRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_document_new', methods: ['GET', 'POST'])]
    public function new(Request $request, DocumentRepository $documentRepository): Response
    {
        $document = new Document();
        $form = $this->createForm(DocumentType::class, $document);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $documentRepository->save($document, true);

            return $this->redirectToRoute('front_app_document_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('front/document/new.html.twig', [
            'document' => $document,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_document_show', methods: ['GET'])]
    public function show(Document $document): Response
    {
        return $this->render('front/document/show.html.twig', [
            'document' => $document,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_document_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Document $document, DocumentRepository $documentRepository): Response
    {
        $form = $this->createForm(DocumentType::class, $document);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $documentRepository->save($document, true);

            return $this->redirectToRoute('front_app_document_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('front/document/edit.html.twig', [
            'document' => $document,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_document_delete', methods: ['POST'])]
    public function delete(Request $request, Document $document, DocumentRepository $documentRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$document->getId(), $request->request->get('_token'))) {
            $documentRepository->remove($document, true);
        }

        return $this->redirectToRoute('front_app_document_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/front/event/_delete_form.html.twig
<form method="post" action="{{ path('front_app_event_delete', {'id': event.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ event.id) }}">
    <button class="delete">Delete</button>
</form>

templates/front/event/_form.html.twig
{{ form_start(form) }}
    <div class="input-container">
        {{ form_label(form.title) }}
        {{ form_widget(form.title) }}
    </div>
    <div class="input-container">
        {{ form_label(form.description) }}
        {{ form_widget(form.description) }}
    </div>
    <div class="input-container">
        {{ form_label(form.lieu) }}
        {{ form_widget(form.lieu) }}
    </div>
    <div class="checkbox-container">
        {{ form_label(form.public) }}
        {{ form_widget(form.public) }}
    </div>
    <div class="checkbox-container">
        {{ form_label(form.event_start) }}
        {{ form_widget(form.event_start) }}
    </div>
    <div class="checkbox-container">
        {{ form_label(form.event_end) }}
        {{ form_widget(form.event_end) }}
    </div>
    <div class="checkbox-container">
        {{ form_label(form.text_color) }}
        {{ form_widget(form.text_color) }}
    </div>
    <div class="checkbox-container">
        {{ form_label(form.background_color) }}
        {{ form_widget(form.background_color) }}
    </div>
    <div class="checkbox-container">
        {{ form_label(form.border_color) }}
        {{ form_widget(form.border_color) }}
    </div>
    <div class="input-container">
        {{ form_label(form.invite) }}
        {{ form_widget(form.invite) }}
    </div>

    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

<script>    
     $(document).ready(function() {
        $('.js-example-basic-multiple').select2();
    });
</script>

templates/front/event/_input_textarea.html.twig
{{ form_start(form) }}


<div class="input-text-firstname">
    {{ form_label(form.firstname) }}
    {{ form_widget(form.firstname) }}
</div>


<div class="input-text-lastname">
    {{ form_label(form.lastname) }}
    {{ form_widget(form.lastname) }}
</div>


<div class="input-text-email">
    {{ form_label(form.email) }}
    {{ form_widget(form.email) }}
</div>

<div class="input-text-password">
    {{ form_widget(form.password) }}
</div>



{% if form.description is defined %}
    <div class="input-textarea-description">
        {{ form_label(form.description) }}
        {{ form_widget(form.description) }}
    </div>
{% endif %}

{% if form.promotionLink is defined %}
<div class="input-textarea-promotion">
    {{ form_label(form.promotionLink) }}
    {{ form_widget(form.promotionLink) }}
</div>
{% endif %}

{{ form_end(form) }}

templates/front/event/edit.html.twig
{% extends 'base_front.html.twig' %}

{% block body %}
    <section class="event-new">
        <h3>Modifier un évènement</h3>
        {{ form_start(form) }}
            {{ form_widget(form._token) }}
            <div class="input-container">
        {{ form_label(form.title) }}
        {{ form_widget(form.title) }}
    </div>
    <div class="input-container">
        {{ form_label(form.description) }}
        {{ form_widget(form.description) }}
    </div>
    <div class="input-container">
        {{ form_label(form.lieu) }}
        {{ form_widget(form.lieu) }}
    </div>
    <div class="checkbox-container">
        {{ form_label(form.public) }}
        {{ form_widget(form.public) }}
    </div>
    <div class="checkbox-container">
        {{ form_label(form.event_start) }}
        {{ form_widget(form.event_start) }}
    </div>
    <div class="checkbox-container">
        {{ form_label(form.event_end) }}
        {{ form_widget(form.event_end) }}
    </div>
    <div class="checkbox-container">
        {{ form_label(form.text_color) }}
        {{ form_widget(form.text_color) }}
    </div>
    <div class="checkbox-container">
        {{ form_label(form.background_color) }}
        {{ form_widget(form.background_color) }}
    </div>
    <div class="checkbox-container">
        {{ form_label(form.border_color) }}
        {{ form_widget(form.border_color) }}
    </div>

            <div class="input-container">
                {{ form_label(form.invite) }}
                {{ form_widget(form.invite) }}
            </div>
            <div class="button-container">
                <button class="btn">{{ button_label|default('Modifier le groupe') }}</button>
                {{ form_end(form) }}
                {{ include('front/event/_delete_form.html.twig') }}
            </div>
    </section>


    <script>    
            $(document).ready(function() {
                $('.js-example-basic-multiple').select2();

                // Initialiser le tableau des artistes sélectionnés
                const selectedArtists = $('.js-example-basic-multiple').val() || [];

                // Écouter l'événement 'select2:select'
                $('.js-example-basic-multiple').on('select2:select', function (e) {
                    const addedArtistId = e.params.data.id;

                    // Ajouter l'artiste au tableau
                    if (!selectedArtists.includes(addedArtistId)) {
                    selectedArtists.push(addedArtistId);
                    }

                    console.log(selectedArtists); // Afficher le tableau mis à jour
                });

                $('.js-example-basic-multiple').on('select2:unselect', function (e) {
                    const removedArtistId = e.params.data.id;

                    // Retirer l'artiste du tableau
                    const artistIndex = selectedArtists.indexOf(removedArtistId);
                    if (artistIndex > -1) {
                    selectedArtists.splice(artistIndex, 1);
                    }

                    console.log(selectedArtists); // Afficher le tableau mis à jour
                });

                $('form').on('submit', function (e) {
                    // Récupérer la liste des artistes sélectionnés
                    const selectedArtists = $('.js-example-basic-multiple').val() || [];

                    // Ajouter la liste des artistes sélectionnés dans un champ caché du formulaire
                    $('input[name="selected_artists"]').val(selectedArtists.join(','));

                    // Continuer la soumission du formulaire
                    return true;
                });
            });
            
        </script>
{% endblock %}

templates/front/event/index.html.twig
{% extends 'base_front.html.twig' %}

{% block body %}
    <section class="event-index">
        <h1>Liste des évènements</h1>
        {% for event in events %}
            <a class="event-card" href="{{ path('front_app_event_show', {'id': event.id}) }}">
                <div class="header">
                    <span>{{ event.musicGroup.name }} à {{ event.lieu }}</span>
                    <span>{{ event.eventStart ? event.eventStart|date('Y-m-d') : '' }}</span>
                </div>
                <h5>{{ event.title }}</h5>
                <p>{{ event.description }}</p>
            </a>
        {% endfor %}

    </section>
{% endblock %}

templates/front/event/new.html.twig
{% extends 'base_front.html.twig' %}

{% block body %}

    <section class="event-new">
        <h3>Créer un évènement</h3>
        {{ include('front/event/_form.html.twig') }}
    </section>
{% endblock %}

templates/front/event/show.html.twig
{% extends 'base_front.html.twig' %}


{% block body %}
    <section class="event-show">

        <h3>{{ event.title }}</h3>
        <div class="invite">
            <span>Invités :</span>
            <ul>

            {% for invite in invites %}
                <li>{{invite.firstname}}</li>
                {% else %}
                0 invités
            {% endfor %}
            </ul>
        </div>
        <p>{{ event.description }}</p>
        <div class="infos">
            <span><i class="fa-solid fa-location-dot"></i> {{ event.lieu }}</span>
            <span><i class="fa-solid fa-calendar-days"></i> {{ event.eventStart ? event.eventStart|date('Y-m-d') : '' }} - {{ event.eventEnd ? event.eventEnd|date('Y-m-d') : '' }}</span>
        </div>
    
    </section>


    <a href="{{ path('front_app_event_edit', {'id': event.id}) }}">edit</a>

{% endblock %}